name: check-js
on: [push]

jobs:
  init:
    name: Fetch & build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: npm install

      - name: Run Jasmine
        run: |
          # export DISPLAY=:0
          npx karma start --single-run
